package entity;
// Generated May 22, 2017 7:24:23 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Accounts generated by hbm2java
 */
public class Accounts implements java.io.Serializable {

	private static final long serialVersionUID = 6580549910842932153L;
	private Integer accountId;
	private String name;
	private String username;
	private Boolean gender;
	private String email;
	private String linkImg;
	private String passwords;
	private Boolean isLock;
	private Date createDate;
	private Float money;
	private Integer levels;
	private Boolean isActive;
	private String activeCode;
	private Set<Exchanges> exchangeses = new HashSet<Exchanges>(0);
	private Set<Library> libraries = new HashSet<Library>(0);
	private Set<Book> books = new HashSet<Book>(0);

	public Accounts() {
	}

	public Accounts(String email, String username, String passwords, Date createDate) {
		this.email = email;
		this.username = username;
		this.passwords = passwords;
		this.createDate = createDate;
	}

	public Accounts(String name, String username, Boolean gender, String email, String linkImg, String passwords) {
		super();
		this.name = name;
		this.username = username;
		this.gender = gender;
		this.email = email;
		this.linkImg = linkImg;
		this.passwords = passwords;
	}

	public Accounts(String name, String username, Boolean gender, String email, String linkImg, String passwords,
			Boolean isLock, Date createDate, Float money, Integer levels) {
		super();
		this.name = name;
		this.gender = gender;
		this.username = username;
		this.email = email;
		this.linkImg = linkImg;
		this.passwords = passwords;
		this.isLock = isLock;
		this.createDate = createDate;
		this.money = money;
		this.levels = levels;
	}

	public Accounts(Integer accountId, String name, String username, Boolean gender, String email, String linkImg,
			String passwords, Boolean isLock, Date createDate, Float money, Integer levels, Set<Exchanges> exchangeses,
			Set<Library> libraries, Set<Book> books) {
		super();
		this.accountId = accountId;
		this.name = name;
		this.username = username;
		this.gender = gender;
		this.email = email;
		this.linkImg = linkImg;
		this.passwords = passwords;
		this.isLock = isLock;
		this.createDate = createDate;
		this.money = money;
		this.levels = levels;
		this.exchangeses = exchangeses;
		this.libraries = libraries;
		this.books = books;
	}

	public Accounts(String name, String username, Boolean gender, String email, String linkImg, String passwords,
			Boolean isLock, Date createDate, Float money, Integer levels, boolean isActive, String activeCode) {
		super();
		this.name = name;
		this.username = username;
		this.gender = gender;
		this.email = email;
		this.linkImg = linkImg;
		this.passwords = passwords;
		this.isLock = isLock;
		this.createDate = createDate;
		this.money = money;
		this.levels = levels;
		this.isActive = isActive;
		this.activeCode = activeCode;
	}

	public Accounts(Integer accountId, String name, String username, Boolean gender, String email, String linkImg,
			String passwords, Boolean isLock, Date createDate, Float money, Integer levels, boolean isActive,
			String activeCode, Set<Exchanges> exchangeses, Set<Library> libraries, Set<Book> books) {
		super();
		this.accountId = accountId;
		this.name = name;
		this.username = username;
		this.gender = gender;
		this.email = email;
		this.linkImg = linkImg;
		this.passwords = passwords;
		this.isLock = isLock;
		this.createDate = createDate;
		this.money = money;
		this.levels = levels;
		this.isActive = isActive;
		this.activeCode = activeCode;
		this.exchangeses = exchangeses;
		this.libraries = libraries;
		this.books = books;
	}

	public Integer getAccountId() {
		return accountId;
	}

	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPasswords() {
		return passwords;
	}

	public void setPasswords(String passwords) {
		this.passwords = passwords;
	}

	public Boolean getIsLock() {
		return isLock;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Boolean getGender() {
		return gender;
	}

	public void setGender(Boolean gender) {
		this.gender = gender;
	}

	public void setIsLock(Boolean isLock) {
		this.isLock = isLock;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Float getMoney() {
		return money;
	}

	public void setMoney(Float money) {
		this.money = money;
	}

	public Integer getLevels() {
		return levels;
	}

	public void setLevels(Integer levels) {
		this.levels = levels;
	}

	public Set<Exchanges> getExchangeses() {
		return exchangeses;
	}

	public void setExchangeses(Set<Exchanges> exchangeses) {
		this.exchangeses = exchangeses;
	}

	public Set<Library> getLibraries() {
		return libraries;
	}

	public void setLibraries(Set<Library> libraries) {
		this.libraries = libraries;
	}

	public Set<Book> getBooks() {
		return books;
	}

	public void setBooks(Set<Book> books) {
		this.books = books;
	}

	public String getLinkImg() {
		return linkImg;
	}

	public void setLinkImg(String linkImg) {
		this.linkImg = linkImg;
	}

	public Boolean getIsActive() {
		return isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	public String getActiveCode() {
		return activeCode;
	}

	public void setActiveCode(String activeCode) {
		this.activeCode = activeCode;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Accounts [accountId=");
		builder.append(accountId);
		builder.append(", name=");
		builder.append(name);
		builder.append(", username=");
		builder.append(username);
		builder.append(", gender=");
		builder.append(gender);
		builder.append(", email=");
		builder.append(email);
		builder.append(", linkImg=");
		builder.append(linkImg);
		builder.append(", passwords=");
		builder.append(passwords);
		builder.append(", isLock=");
		builder.append(isLock);
		builder.append(", createDate=");
		builder.append(createDate);
		builder.append(", money=");
		builder.append(money);
		builder.append(", levels=");
		builder.append(levels);
		builder.append(", exchangeses=");
		builder.append(exchangeses);
		builder.append(", libraries=");
		builder.append(libraries);
		builder.append(", books=");
		builder.append(books);
		builder.append("]");
		return builder.toString();
	}

}
