package entity;
// Generated May 22, 2017 7:24:23 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Book generated by hbm2java
 */
public class Book implements java.io.Serializable {

	private static final long serialVersionUID = -7111256618114772148L;
	private Integer bookId;
	private String bookName;
	private String slug;
	private Boolean state;
	private Integer age;
	private String introduction;
	private Date postDate;
	private String linkImg;
	private String country;
	private Float price;
	private Boolean checked;
	private Integer likes;
	private Integer subcribe;
	private Set<Exchanges> exchangeses = new HashSet<>(0);
	private Set<Library> likelib = new HashSet<>(0);
	private Set<Chapter> chapters = new HashSet<>(0);
	private Set<Accounts> book_author = new HashSet<>(0);
	private Set<Library> subcribelib = new HashSet<>(0);
	private Set<Category> categories = new HashSet<>(0);

	public Book() {
	}

	public Book(String slug, Date postDate) {
		this.slug = slug;
		this.postDate = postDate;
	}

	public Book(String bookName, String slug, Boolean state, Integer age, String introduction, Date postDate,
			String linkImg, String country, Float price, Boolean checked, Integer likes, Set<Chapter> chapters,
			Set<Accounts> book_author, Set<Category> categories) {
		super();
		this.bookName = bookName;
		this.slug = slug;
		this.state = state;
		this.age = age;
		this.introduction = introduction;
		this.postDate = postDate;
		this.linkImg = linkImg;
		this.country = country;
		this.price = price;
		this.checked = checked;
		this.likes = likes;
		this.chapters = chapters;
		this.book_author = book_author;
		this.categories = categories;
	}

	public Book(Integer bookId, String bookName, String slug, Boolean state, Integer age, String introduction,
			Date postDate, String linkImg, String country, Float price, Boolean checked, Integer likes,
			Integer subcribe, Set<Exchanges> exchangeses, Set<Library> likelib, Set<Chapter> chapters,
			Set<Accounts> book_author, Set<Library> subcribelib, Set<Category> categories) {
		super();
		this.bookId = bookId;
		this.bookName = bookName;
		this.slug = slug;
		this.state = state;
		this.age = age;
		this.introduction = introduction;
		this.postDate = postDate;
		this.linkImg = linkImg;
		this.country = country;
		this.price = price;
		this.checked = checked;
		this.likes = likes;
		this.subcribe = subcribe;
		this.exchangeses = exchangeses;
		this.likelib = likelib;
		this.chapters = chapters;
		this.book_author = book_author;
		this.subcribelib = subcribelib;
		this.categories = categories;
	}

	public Book(String bookName, String slug, Boolean state, Integer age, String introduction, Date postDate,
			String linkImg, String country, Float price, Integer likes, Boolean checked, Integer subcribe,
			Set<Exchanges> exchangeses, Set<Library> likelib, Set<Chapter> chapters, Set<Accounts> book_author,
			Set<Library> subcribelib, Set<Category> categories) {
		super();
		this.bookName = bookName;
		this.slug = slug;
		this.state = state;
		this.age = age;
		this.introduction = introduction;
		this.postDate = postDate;
		this.linkImg = linkImg;
		this.country = country;
		this.price = price;
		this.likes = likes;
		this.checked = checked;
		this.subcribe = subcribe;
		this.exchangeses = exchangeses;
		this.likelib = likelib;
		this.chapters = chapters;
		this.book_author = book_author;
		this.subcribelib = subcribelib;
		this.categories = categories;
	}

	public Integer getBookId() {
		return bookId;
	}

	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}

	public String getBookName() {
		return bookName;
	}

	public void setBookName(String bookName) {
		this.bookName = bookName;
	}

	public String getSlug() {
		return slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}

	public Boolean getState() {
		return state;
	}

	public void setState(Boolean state) {
		this.state = state;
	}

	public Integer getAge() {
		return age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getIntroduction() {
		return introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	public Date getPostDate() {
		return postDate;
	}

	public void setPostDate(Date postDate) {
		this.postDate = postDate;
	}

	public String getLinkImg() {
		return linkImg;
	}

	public void setLinkImg(String linkImg) {
		this.linkImg = linkImg;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public Float getPrice() {
		return price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	public Boolean getChecked() {
		return checked;
	}

	public void setChecked(Boolean checked) {
		this.checked = checked;
	}

	public Integer getLikes() {
		return likes;
	}

	public void setLikes(Integer likes) {
		this.likes = likes;
	}

	public Integer getSubcribe() {
		return subcribe;
	}

	public void setSubcribe(Integer subcribe) {
		this.subcribe = subcribe;
	}

	public Set<Exchanges> getExchangeses() {
		return exchangeses;
	}

	public void setExchangeses(Set<Exchanges> exchangeses) {
		this.exchangeses = exchangeses;
	}

	public Set<Library> getLikelib() {
		return likelib;
	}

	public void setLikelib(Set<Library> likelib) {
		this.likelib = likelib;
	}

	public Set<Chapter> getChapters() {
		return chapters;
	}

	public void setChapters(Set<Chapter> chapters) {
		this.chapters = chapters;
	}

	public Set<Accounts> getBook_author() {
		return book_author;
	}

	public void setBook_author(Set<Accounts> book_author) {
		this.book_author = book_author;
	}

	public Set<Library> getSubcribelib() {
		return subcribelib;
	}

	public void setSubcribelib(Set<Library> subcribelib) {
		this.subcribelib = subcribelib;
	}

	public Set<Category> getCategories() {
		return categories;
	}

	public void setCategories(Set<Category> categories) {
		this.categories = categories;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Book [bookId=");
		builder.append(bookId);
		builder.append(", bookName=");
		builder.append(bookName);
		builder.append(", slug=");
		builder.append(slug);
		builder.append(", state=");
		builder.append(state);
		builder.append(", age=");
		builder.append(age);
		builder.append(", introduction=");
		builder.append(introduction);
		builder.append(", postDate=");
		builder.append(postDate);
		builder.append(", linkImg=");
		builder.append(linkImg);
		builder.append(", country=");
		builder.append(country);
		builder.append(", price=");
		builder.append(price);
		builder.append(", checked=");
		builder.append(checked);
		builder.append(", likes=");
		builder.append(likes);
		builder.append(", subcribe=");
		builder.append(subcribe);
		builder.append("]");
		return builder.toString();
	}

	public int getNewestChapter() {
		if (chapters.size() > 0) {
			int max = Integer.MIN_VALUE;
			for (Chapter c : chapters) {
				if (max < c.getOrders())
					max = c.getOrders();
			}
			return max;
		}
		return 0;
	}
}
