package entity;
// Generated May 22, 2017 7:24:23 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Chapter generated by hbm2java
 */
public class Chapter implements java.io.Serializable {

	private static final long serialVersionUID = -1650943527020983949L;
	private Integer chapterId;
	private Book book;
	private Integer orders;
	private String chapterName;
	private String slug;
	private Date postDate;
	private Boolean isRead;
	private Integer likes;
	private Set<ChapterContent> chapterContents = new HashSet<ChapterContent>(0);
	private Set<Exchanges> exchangeses = new HashSet<Exchanges>(0);

	public Chapter() {
	}

	public Chapter(Date postDate) {
		this.postDate = postDate;
	}

	public Chapter(Integer chapterId, Book book, Integer orders, String chapterName, String slug, Date postDate,
			Boolean isRead, Integer likes, Set<ChapterContent> chapterContents, Set<Exchanges> exchangeses) {
		super();
		this.chapterId = chapterId;
		this.book = book;
		this.orders = orders;
		this.chapterName = chapterName;
		this.slug = slug;
		this.postDate = postDate;
		this.isRead = isRead;
		this.likes = likes;
		this.chapterContents = chapterContents;
		this.exchangeses = exchangeses;
	}

	public Chapter(Book book, Integer orders, String chapterName, String slug, Date postDate, Boolean isRead,
			Integer likes, Set<ChapterContent> chapterContents, Set<Exchanges> exchangeses) {
		super();
		this.book = book;
		this.orders = orders;
		this.chapterName = chapterName;
		this.slug = slug;
		this.postDate = postDate;
		this.isRead = isRead;
		this.likes = likes;
		this.chapterContents = chapterContents;
		this.exchangeses = exchangeses;
	}

	public Integer getChapterId() {
		return chapterId;
	}

	public void setChapterId(Integer chapterId) {
		this.chapterId = chapterId;
	}

	public Book getBook() {
		return book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	public Integer getOrders() {
		return orders;
	}

	public void setOrders(Integer orders) {
		this.orders = orders;
	}

	public String getChapterName() {
		return chapterName;
	}

	public void setChapterName(String chapterName) {
		this.chapterName = chapterName;
	}

	public String getSlug() {
		return slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}

	public Date getPostDate() {
		return postDate;
	}

	public void setPostDate(Date postDate) {
		this.postDate = postDate;
	}

	public Boolean getIsRead() {
		return isRead;
	}

	public void setIsRead(Boolean isRead) {
		this.isRead = isRead;
	}

	public Integer getLikes() {
		return likes;
	}

	public void setLikes(Integer likes) {
		this.likes = likes;
	}

	public Set<ChapterContent> getChapterContents() {
		return chapterContents;
	}

	public void setChapterContents(Set<ChapterContent> chapterContents) {
		this.chapterContents = chapterContents;
	}

	public Set<Exchanges> getExchangeses() {
		return exchangeses;
	}

	public void setExchangeses(Set<Exchanges> exchangeses) {
		this.exchangeses = exchangeses;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Chapter [chapterId=");
		builder.append(chapterId);
		builder.append(", book=");
		builder.append(book);
		builder.append(", orders=");
		builder.append(orders);
		builder.append(", chapterName=");
		builder.append(chapterName);
		builder.append(", slug=");
		builder.append(slug);
		builder.append(", postDate=");
		builder.append(postDate);
		builder.append(", isRead=");
		builder.append(isRead);
		builder.append(", likes=");
		builder.append(likes);
		builder.append(", chapterContents=");
		builder.append(chapterContents);
		builder.append("]");
		return builder.toString();
	}


}
