package entity;
// Generated May 22, 2017 7:24:23 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Exchanges generated by hbm2java
 */
public class Exchanges implements java.io.Serializable {

	private static final long serialVersionUID = 8022486892847784337L;
	private Integer exchangeId;
	private Accounts accounts;
	private Book book;
	private Chapter chapter;
	private Date xtime;
	private Float amount;

	public Exchanges() {
	}

	public Exchanges(Date xtime) {
		this.xtime = xtime;
	}

	public Exchanges(Accounts accounts, Book book, Chapter chapter, Date xtime, Float amount) {
		this.accounts = accounts;
		this.book = book;
		this.chapter = chapter;
		this.xtime = xtime;
		this.amount = amount;
	}

	public Integer getExchangeId() {
		return exchangeId;
	}

	public void setExchangeId(Integer exchangeId) {
		this.exchangeId = exchangeId;
	}

	public Accounts getAccounts() {
		return accounts;
	}

	public void setAccounts(Accounts accounts) {
		this.accounts = accounts;
	}

	public Book getBook() {
		return book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	public Chapter getChapter() {
		return chapter;
	}

	public void setChapter(Chapter chapter) {
		this.chapter = chapter;
	}

	public Date getXtime() {
		return xtime;
	}

	public void setXtime(Date xtime) {
		this.xtime = xtime;
	}

	public Float getAmount() {
		return amount;
	}

	public void setAmount(Float amount) {
		this.amount = amount;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Exchanges [Id=");
		builder.append(exchangeId);
		builder.append(", accounts=");
		builder.append(accounts);
		builder.append(", book=");
		builder.append(book);
		builder.append(", chapter=");
		builder.append(chapter);
		builder.append(", time=");
		builder.append(xtime);
		builder.append(", amount=");
		builder.append(amount);
		builder.append("]");
		return builder.toString();
	}

}
