package entity;
// Generated May 22, 2017 7:24:23 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Library generated by hbm2java
 */
public class Library implements java.io.Serializable {

	private static final long serialVersionUID = 3694300144970659338L;
	private Integer libId;
	private Accounts accounts;
	private Set<Book> likelib = new HashSet<>(0);
	private Set<Book> subcribelib = new HashSet<>(0);

	public Library() {
	}

	public Library(Accounts accounts) {
		this.accounts = accounts;
	}

	public Library(Accounts accounts, Set<Book> books, Set<Book> listSubcribe) {
		this.accounts = accounts;
		this.likelib = books;
		this.subcribelib = listSubcribe;
	}

	public Library(Integer libId, Accounts accounts, Set<Book> likelib, Set<Book> subcribelib) {
		super();
		this.libId = libId;
		this.accounts = accounts;
		this.likelib = likelib;
		this.subcribelib = subcribelib;
	}

	public Integer getLibId() {
		return libId;
	}

	public void setLibId(Integer libId) {
		this.libId = libId;
	}

	public Accounts getAccounts() {
		return accounts;
	}

	public void setAccounts(Accounts accounts) {
		this.accounts = accounts;
	}

	public Set<Book> getLikelib() {
		return likelib;
	}

	public void setLikelib(Set<Book> likelib) {
		this.likelib = likelib;
	}

	public Set<Book> getSubcribelib() {
		return subcribelib;
	}

	public void setSubcribelib(Set<Book> subcribelib) {
		this.subcribelib = subcribelib;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Library [libId=");
		builder.append(libId);
		builder.append(", accounts=");
		builder.append(accounts);
		builder.append(", likelib=");
		builder.append(likelib);
		builder.append(", subcribelib=");
		builder.append(subcribelib);
		builder.append("]");
		return builder.toString();
	}

}
