package entity;

import org.hibernate.annotations.Entity;

// Generated May 22, 2017 7:24:23 PM by Hibernate Tools 5.2.3.Final

/**
 * Manager generated by hbm2java
 */
@SuppressWarnings("deprecation")
@Entity
public class Manager implements java.io.Serializable {

	private static final long serialVersionUID = -742005922226676702L;
	private int accountId;
	private Accounts accounts;
	private String office;

	public Manager() {
	}

	public Manager(int accountId, Accounts accounts, String office) {
		super();
		this.accountId = accountId;
		this.accounts = accounts;
		this.office = office;
	}

	public Manager(Accounts accounts) {
		this.accounts = accounts;
	}

	public Manager(Accounts accounts, String office) {
		this.accountId = accounts.getAccountId();
		this.accounts = accounts;
		this.office = office;
	}

	public int getAccountId() {
		return accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	public Accounts getAccounts() {
		return accounts;
	}

	public void setAccounts(Accounts accounts) {
		this.accounts = accounts;
	}

	public String getOffice() {
		return office;
	}

	public void setOffice(String office) {
		this.office = office;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Manager [accountId=");
		builder.append(accountId);
		builder.append(", accounts=");
		builder.append(accounts);
		builder.append(", office=");
		builder.append(office);
		builder.append("]");
		return builder.toString();
	}

}
